In [ ]:
%pip install shap

import pandas as pd
import matplotlib.pyplot as plt
import shap

ModuleNotFoundError: No module named 'shap'

In [2]:
babies = pd.read_csv(r'C:\Users\mimarqu\Downloads\babies.csv')
babies.head()

   case  bwt  gestation  parity   age  height  weight  smoke
0     1  120      284.0       0  27.0    62.0   100.0    0.0
1     2  113      282.0       0  33.0    64.0   135.0    0.0
2     3  128      279.0       0  28.0    64.0   115.0    1.0
3     4  123        NaN       0  36.0    69.0   190.0    0.0
4     5  108      282.0       0  23.0    67.0   125.0    1.0

- Age: Age in years when a woman is pregnant.
- SystolicBP: Upper value of Blood Pressure in mmHg, another significant attribute during pregnancy.
- DiastolicBP: Lower value of Blood Pressure in mmHg, another significant attribute during pregnancy.
- BS: Blood glucose levels is in terms of a molar concentration, mmol/L.
- HeartRate: A normal resting heart rate in beats per minute.
- Risk Level: Predicted Risk Intensity Level during pregnancy considering the previous attribute.

In [3]:
maternal_health_risk = pd.read_csv(r'C:\Users\mimarqu\Downloads\Maternal Health Risk Data Set.csv')
maternal_health_risk.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

- case
id number
- bwt
birthweight, in ounces
- gestation
length of gestation, in days
- parity
binary indicator for a first pregnancy (0 = first pregnancy)
- age
mother's age in years
- height
mother's height in inches
- weight
mother's weight in pounds
- smoke
binary indicator for whether the mother smokes